<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Gateway-PC" name="com.schemaxtech.testAutomationFrameworkTest.Surplus" tests="13" failures="6" timestamp="21 Dec 2019 09:20:22 GMT" time="4.228" errors="1">
  <testcase name="CreateSurpluslocation" time="0.048" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
  <testcase name="CreateSurpluslocation" time="2.773" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;errorInfo&#039; with value &#039;Success&#039; in response json failed expected [Success] but found [Surplus Location Category Doesnot exist.]">
      <![CDATA[java.lang.AssertionError: Verification of 'errorInfo' with value 'Success' in response json failed expected [Success] but found [Surplus Location Category Doesnot exist.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.CreateSurpluslocation(Surplus.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CreateSurpluslocation -->
  <testcase name="CreateSurpluslocation" time="0.086" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;errorInfo&#039; with value &#039;Surplus Location Code already exist.&#039; in response json failed expected [Surplus Location Code already exist.] but found [Surplus Location Category Doesnot exist.]">
      <![CDATA[java.lang.AssertionError: Verification of 'errorInfo' with value 'Surplus Location Code already exist.' in response json failed expected [Surplus Location Code already exist.] but found [Surplus Location Category Doesnot exist.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.CreateSurpluslocation(Surplus.java:66)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- CreateSurpluslocation -->
  <testcase name="CreateSurpluslocation" time="0.097" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
  <testcase name="UpdateSurpluslocation" time="0.120" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;errorInfo&#039; with value &#039;Surplus Location Updated Sucessfully&#039; in response json failed expected [Surplus Location Updated Sucessfully] but found [Surplus Location Code already exist.]">
      <![CDATA[java.lang.AssertionError: Verification of 'errorInfo' with value 'Surplus Location Updated Sucessfully' in response json failed expected [Surplus Location Updated Sucessfully] but found [Surplus Location Code already exist.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.UpdateSurpluslocation(Surplus.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- UpdateSurpluslocation -->
  <testcase name="UpdateSurpluslocation" time="0.119" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
  <testcase name="UpdateSurpluslocation" time="0.234" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
  <testcase name="UpdateSurpluslocation" time="0.076" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;errorInfo&#039; with value &#039;Surplus Location Updated Sucessfully&#039; in response json failed expected [Surplus Location Updated Sucessfully] but found [Surplus Location Code already exist.]">
      <![CDATA[java.lang.AssertionError: Verification of 'errorInfo' with value 'Surplus Location Updated Sucessfully' in response json failed expected [Surplus Location Updated Sucessfully] but found [Surplus Location Code already exist.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.UpdateSurpluslocation(Surplus.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- UpdateSurpluslocation -->
  <testcase name="getSurpluslocation" time="0.123" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
  <testcase name="getSurpluslocation" time="0.158" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;status&#039; with value &#039;true&#039; in response json failed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Verification of 'status' with value 'true' in response json failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.getSurpluslocation(Surplus.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- getSurpluslocation -->
  <testcase name="getSurpluslocation" time="0.138" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <error type="java.lang.Exception" message="Given value not found in response json">
      <![CDATA[java.lang.Exception: Given value not found in response json
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:356)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.getSurpluslocation(Surplus.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- getSurpluslocation -->
  <testcase name="deactivateSurpluslocation" time="0.096" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus">
    <failure type="java.lang.AssertionError" message="Verification of &#039;errorInfo&#039; with value &#039;successfully deactivated.&#039; in response json failed expected [successfully deactivated.] but found [surplusLocation not found.]">
      <![CDATA[java.lang.AssertionError: Verification of 'errorInfo' with value 'successfully deactivated.' in response json failed expected [successfully deactivated.] but found [surplusLocation not found.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at com.schemaxtech.testAutomationFramework.TestAutomationUtil.verifyResponse(TestAutomationUtil.java:345)
at com.schemaxtech.testAutomationFrameworkTest.Surplus.deactivateSurpluslocation(Surplus.java:96)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- deactivateSurpluslocation -->
  <testcase name="deactivateSurpluslocation" time="0.160" classname="com.schemaxtech.testAutomationFrameworkTest.Surplus"/>
</testsuite> <!-- com.schemaxtech.testAutomationFrameworkTest.Surplus -->
